import mongoose from "mongoose";

const GeneratedPdfSchema = new mongoose.Schema({
    url: {
        type: String,
        required: [true, "Pdf Url is required"],
        trim: true,
    },
    generatedBy: {
        type: mongoose.Schema.Types.ObjectId, ref: 'User',
        // required: [true, "Generated By is required"],
    },
    tags: {
        type: Array,
    },
    visibility: {
        type: Boolean,
        default: false,
    }
}, {
    timestamps: true
});


export const PdfModel =  mongoose.model("GeneratedPdf", GeneratedPdfSchema);

